export const ADD_CURRENCIES = "ADD_CURRENCIES";
export const CURRENCIES_LOADING = "CURRENCIES_LOADING";
export const CURRENCIES_FAILED = "CURRENCIES_FAILED";
export const SELECT_CRYPTO = "SELECT_CRYPTO";
export const SELECT_CRYPTO_LOADING = "SELECT_CRYPTO_LOADING";
export const SELECT_CRYPTO_FAILED = "SELECT_CRYPTO_FAILED";